### ISSUE TITLE
Switch to method for testing single point?

### ISSUE THREAD

**Issue by veltman** [veltman/mahalanobis#3]
Instead of calculating the distances within the data, might be better to return a function to test any point against that distribution.  e.g.:

``` js
mahalanobis(someData).distance(point) // return distance of point using means and covariance defined by someData
```

Maybe with a convenience method for checking the data against itself:

``` js
mahalanobis(someData).all() // return array of distances for someData
```

**Comment by inesani** [comment]
@veltman I am very interested on this method :) Any chance this has been done or the PR merged ? Thanks

**Comment by veltman** [comment]
@inesani this is done in v1.0.0.
